### Testar a raiz do projeto 
GET http://localhost:5272

### Cadastrar um usuário
POST http://localhost:5272/api/usuario/cadastrar
Content-Type: application/json

{
    "CPF": "11111111111",
    "NomeCompleto": "João Silva",
    "Celular": "11999999999",
    "Email": "joao.silva@email.com",
    "Senha": "senhaSegura123"
}

### Alterar informações de um usuário (por CPF)
PUT http://localhost:5272/api/usuario/alterar/01987654321
Content-Type: application/json

{
    "NomeCompleto": "João Silva NOVO",
    "Celular": "11888888888",
    "Email": "joao.silva@novodominio.com",
    "Senha": "novaSenhaSegura123"
}

### Listar todos os usuários
GET http://localhost:5272/api/usuario/listar

### Buscar um usuário pelo CPF
GET http://localhost:5272/api/usuario/buscar/01987654321

### Deletar um usuário pelo CPF
DELETE http://localhost:5272/api/usuario/deletar/01987654321
