### Cadastrar um veiculo
POST http://localhost:5272/api/veiculo/cadastrar
Content-Type: application/json

{
    "Placa": "ABC123",
    "Modelo": "Camaro",
    "Marca": "Chevrolet",
    "Ano": "2025"
}

### Listar todos os veiculos
GET http://localhost:5272/api/veiculo/listarTudo

### Buscar um veiculo pelo Placa
GET http://localhost:5272/api/veiculo/buscar/ABC123

### Deletar um veiculo pelo Placa
DELETE http://localhost:5272/api/veiculo/deletar/ABC123

